Post/urls.py
from django.conf.urls import url
from . import views

app_name = 'post'

urlpatterns = [
    url(r'^(?P<post_id>[0-9]+)', views.get_post, name='get_post'),
]

SocialNetworkNew/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^post/',include('Post.urls')),
    url(r'^user/', include('User.urls')),
    url(r'^admin/', admin.site.urls),
]

User/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^all/$',views.get_all_users,name='all_user'),
    url(r'^register/$',views.register_user,name='register'),
    url(r'^login/$',views.login_user,name='login'),
    url(r'^logout/',views.logout_user,name='logout'),
    url(r'^profile/(?P<user_email>[\w.@\-]+)/',views.user_profile,name='profile'),
    url(r'^profile/',views.show_profile,name="show_profile"),
    url(r'^create_article$',views.create_article,name='create_article'),
    url(r'^friends',views.show_friends,name='friends'),
]

Friends/models.py
from __future__ import unicode_literals

from django.db import models
from User.models import CustomUser


class Friend(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user_email = models.EmailField(max_length=255)
    friend_email = models.EmailField(max_length=255)
    friend_type = models.CharField(max_length=50)
    request_type = models.CharField(max_length=20)
    friend_since = models.DateTimeField(null=True)

    class Meta:
        unique_together = (('user_email', 'friend_email'), ('friend_email', 'user_email'))

    def __str__(self):
        return self.user_email + " -> " + self.friend_email + "  || Status : " + self.request_type + " ||"

    def get_friend_username(self):
        return self.friend_email.split('@')[0]

    def get_username(self):
        return self.user_email.split('@')[0]


class RequestList(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    user_email = models.EmailField(max_length=255)
    requested_user_email = models.EmailField(max_length=255)
    request_date = models.DateTimeField()
    request_type = models.CharField(max_length=20)

    class Meta:
        unique_together = (('user_email', 'requested_user_email'),
                           ('requested_user_email', 'user_email'))

    def __str__(self):
        return self.user_email + " || Request from -> " + self.requested_user_email + "  || Status : " + self.request_type + " ||"

    def get_username(self):
        return self.requested_user_email.split('@')[0]

User/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)
from django.conf import settings


# Create your models here.

class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, date_of_birth, password):
        if not email:
            raise ValueError("You must specify a valid email")
        user = self.model(
            email=self.normalize_email(email),
            password=password,
            first_name=first_name,
            last_name=last_name,
            date_of_birth=date_of_birth,
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, date_of_birth, password):
        user = self.create_user(email=email, password=password, first_name=first_name, last_name=last_name,
                                date_of_birth=date_of_birth)
        user.is_admin = True
        user.save()
        return user


class CustomUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'date_of_birth']

    class Meta:
        verbose_name = 'CustomUser'

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def get_username(self):
        return self.email.split('@')[0]


class ProfileCustomer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    about = models.CharField(max_length=500)
    gender = models.CharField(max_length=20)

Friends/views.py
from django.shortcuts import render

# Create your views here.

User/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from .form_auth import CustomUserForm, LoginForm, PostForm
from .models import CustomUser
from django.core.exceptions import ObjectDoesNotExist
from Friends.models import Friend, RequestList
from Friends.status import Status
from django.utils import timezone
from django.db import IntegrityError
from Post.models import Post, PostLikes


def register_user(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.is_admin = True
            user.save()
            return HttpResponse("Registration Successful")
    else:
        form = CustomUserForm()
    return render(request, "User/register.html", {"form": form, "button_text": "Register"})


def login_user(request):
    if request.user.is_authenticated():
        return redirect('user:profile', user_email=request.user.email)
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                user = authenticate(email=email, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        if request.GET.get(
                                'next'):  # To check if the user tried to access a page where login was required
                            return redirect(request.GET.get('next'))
                        return redirect('user:profile', user_email=email)
                    else:
                        return HttpResponse("User is In active")
                else:
                    return HttpResponse("User is not registered")
        else:
            form = LoginForm()
    return render(request, "User/register.html", {"form": form, "button_text": "Login"})


def logout_user(request):
    logout(request)
    return redirect('user:login')


@login_required(login_url='user:login', redirect_field_name='')
def user_profile(request, user_email):
    if request.method == 'GET':
        form = PostForm()
        userFK = get_object_or_404(CustomUser, email=user_email)
        if not request.user.friend_set.filter(friend_email=user_email):
            is_friend="false"
        else:
            is_friend="true"
        posts = userFK.post_set.all().order_by('-created_at')
        users = CustomUser.objects.all()

        if request_already_sent(request, user_email) and can_send_request(request, user_email):
            request_permission = "true"
        else:
            request_permission = "false"
        if request.GET.get('query'):
            starts_with = request.GET.get('query')
            try:
                users = CustomUser.objects.filter(email__startswith=starts_with)
            except ObjectDoesNotExist:
                return HttpResponse('<h5>No user matching your query</h5>')
            return render(request, "User/all_user.html", {"users": users, "current_user": request.user.email,
                                                          "username": request.user.email.split('@')[0]})
        if request.user.email == user_email:
            # If user is the logged in user
            return render(request, "User/profile_new.html",
                          {"full_name": request.user.get_full_name(), "form": form, "posts": posts,
                           "create_post": "true", "email": request.user.get_short_name(), "users": users,
                           "username": request.user.email.split('@')[0],
                           "friend_requests": get_pending_request(request),})
        else:
            # If user is not the logged in user
            return render(request, "User/profile_new.html",
                          {"full_name": request.user.get_full_name(), "posts": posts, "create_post": "false",
                           "email": request.user.email, "users": users,
                           "username": request.user.email.split('@')[0], "user_email": user_email,
                           "can_send_request": request_permission,"is_friend":is_friend})

    if request.method == 'POST':
        if request.POST.get('create', False):
            form = PostForm(request.POST)
            if form.is_valid():
                users = form.save(commit=False)
                users.user = request.user
                users.save()
                return redirect('user:profile', user_email=user_email)
            return HttpResponse("Error Occured")


        elif request.POST.get('logout'):
            logout(request)
            return redirect('user:login')


        elif request.POST.get("add_friend"):
            if send_request(request, user_email):
                return HttpResponse("Request successfully sent")
            return HttpResponse("Request already sent")


        elif request.POST.get("accept_request"):
            requested_user_email = request.POST.get("accept_request")
            accept_request(request, requested_user_email)
            return redirect('user:profile', user_email=request.user.email)


        elif request.POST.get("edit_post"):
            return HttpResponse("Edit Post")


        elif request.POST.get("like_post"):
            try:
                post_id = request.POST.get("like_post")
                post = Post.objects.get(id=post_id)
                post_likes = PostLikes(user=request.user, post=post, liked_at=timezone.now(),
                                       user_email=request.user.email,
                                       post_id_meta=post_id)
                post_likes.save()
                post.likes += 1
                post.save()
            except IntegrityError as e:
                return redirect('user:profile', user_email=user_email)
            return redirect('user:profile', user_email=user_email)


def show_profile(request):
    return render(request, "User/profile_user.html", {"form": None})


@login_required(login_url='user:login')
def get_all_users(request):
    users = CustomUser.objects.all()
    return render(request, "User/all_user.html",
                  {"users": users, "current_user": request.user.email, "username": request.user.email.split('@')[0]})


@login_required(login_url='user:login')
def create_article(request):
    if request.method == 'GET':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.user = request.user
            user.save()
            return redirect('user:profile', user_email=request.user.email)
    return render(request, 'User/create_article.html',
                  {"form": form, "email": request.user.email, "username": request.user.email.split('@')[0]})


def send_request(request, user_email):
    # request:Current user ,user_email:Email of the visited user.
    try:
        requested_user = CustomUser.objects.get(email=user_email)
        request_list = RequestList(user=requested_user, user_email=user_email, requested_user_email=request.user.email,
                                   request_date=timezone.now(), request_type=Status.pending())
        request_list.save()
    except IntegrityError as e:
        return False
    return True


def can_send_request(request, user_email):
    requested_user = RequestList.objects.filter(requested_user_email=user_email, user_email=request.user.email)
    if len(requested_user) == 0:
        return True
    else:
        return False


def request_already_sent(request, user_email):
    requested_user = RequestList.objects.filter(user_email=user_email, requested_user_email=request.user.email)
    if len(requested_user) == 0:
        return True
    else:
        return False


def get_pending_request(request):
    friend_request = RequestList.objects.filter(user_email=request.user.email, request_type=Status.pending())
    return friend_request


def accept_request(request, user_email):
    requested_user = CustomUser.objects.get(email=user_email)
    friend1 = Friend(user=request.user, user_email=request.user.email, friend_email=user_email, friend_type="normal",
                     request_type=Status.accepted(), friend_since=timezone.now())
    friend2 = Friend(user=requested_user, user_email=user_email, friend_email=request.user.email, friend_type="normal",
                     request_type=Status.accepted(), friend_since=timezone.now())
    requestList = RequestList.objects.get(user_email=request.user.email, requested_user_email=user_email)
    requestList.request_type = Status.accepted()
    requestList.save()
    friend1.save()
    friend2.save()


@login_required(login_url='user:login')
def show_friends(request):
    friends = Friend.objects.filter(user_email=request.user.email)
    return render(request, "User/friends.html",
                  {"username": request.user.email.split('@')[0], "email": request.user.email, "friends": friends})

User/templates/User/all_user.html
{% extends 'User/base.html' %}
{% if current_user %}
    {% block nav %}
        <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="{% url 'user:profile' current_user %}">{{ username }}</a>
            <a class="mdl-navigation__link" href="{% url 'user:logout' %}">Logout</a>
        </nav>
    {% endblock %}
{% endif %}
{% block content %}
    {% if users %}
        <ul class="demo-list-item mdl-list">
            {% for user in users %}
                <a href="{% url 'user:profile' user.get_short_name %}">
                    <li class="mdl-list__item">{{ user.get_full_name }}&nbsp;({{ user.get_short_name }})</li>
                </a>
            {% endfor %}
        </ul>
    {% else %}
        <h5 class="error-message">* No user matching your query</h5>
    {% endif %}
{% endblock %}

User/templates/User/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'User/css/profile_style.css' %}">

    {% block custom_style %} {% endblock %}

    <link rel="stylesheet" href="{% static 'User/css/material_icons.css' %}">
    <link rel="stylesheet" href="{% static 'User/css/material-pink.css' %}">
    <script type="text/javascript" src="{% static 'User/js/material-min.js' %}"></script>
    <!---- getmdl styles -->
    <!--<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>-->

    <!---- Bootstrap style -->
    <!--<link rel="stylesheet" href="{% static 'User/bootstrap/dist/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'User/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'User/jquery/dist/jquery.min.js' %}"></script>-->
</head>
<body>
<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row" id="header_row">
            <!-- Title -->
            <span class="mdl-layout-title" id="logo">Social Network</span>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            {% block nav %} {% endblock %}

        </div>
    </header>

    <main class="mdl-layout__content">
        <div class="page-content">
            {% block content %}{% endblock %}
        </div>

    </main>
</div>
</body>
</html>

User/templates/User/create_article.html
{% extends 'User/base.html' %}
{% load staticfiles %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'User/css/login_style.css' %}">
{% endblock %}

{% block nav %}
    <nav class="mdl-navigation mdl-layout--large-screen-only ">
        <a class="mdl-navigation__link" href="{% url 'user:profile' email %}">{{ username }}</a>
        <a class="mdl-navigation__link" href="{% url 'user:logout' %}">Logout</a>
    </nav>
{% endblock %}
{% block content %}
    <div class="post">
        <div class="bar">
            <h3 class="login-title">Create Article</h3>
        </div>
        <form method="post">
            {% csrf_token %}
            <ul>
                {% for field in form %}
                    <li>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            {{ field }}
                            <label class="mdl-textfield__label" for="{{ field.name }}">{{ field.label }}</label>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <button type="submit"
                    class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect"
                    id="btn_create">
                Post Article
            </button>
        </form>
    </div>
{% endblock %}

User/templates/User/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
</head>
<body>
<!-- Numeric Textfield with Floating Label -->
<form action="#">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="sample4">
        <label class="mdl-textfield__label" for="sample4">Number...</label>
        <span class="mdl-textfield__error">Input is not a number!</span>
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="sample4">
        <label class="mdl-textfield__label" for="sample4">Number...</label>
        <span class="mdl-textfield__error">Input is not a number!</span>
    </div>
</form>
</body>
</html>

User/templates/User/friends.html
{% extends 'User/base.html' %}
{% load staticfiles %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'User/css/login_style.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block nav %}
    <a class="mdl-navigation__link" href="{% url 'user:create_article' %}">Create Post</a>
    <a class="mdl-navigation__link" href="{% url 'user:all_user' %}">Users</a>
    <a class="mdl-navigation__link" href="{% url 'user:profile' email %}">{{ username }}</a>
    <a class="mdl-navigation__link" href="{% url 'user:logout' %}">Logout</a>
{% endblock %}
{% block content %}
    {% if friends %}
        <ul>
            {% for f in friends %}
                <li>
                    <a href="{% url 'user:profile' f.friend_email %}"
                       class="mdl-button mdl-js-button mdl-button--raised mdl-button--primary" id="friend-button">{{ f.get_friend_username }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h5>You don't have any friends</h5>
    {% endif %}
{% endblock %}

User/templates/User/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
</head>
<body>
<h1>Welcome {{ full_name }} | {{ email }}</h1>

{% if posts %}
    <ul>
        {% for post in posts %}
            <li>{{ post.title }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post" action="">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    {% if create_post == "true" %}
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit" value="create_post" name="create">Create Post</button>
    {% endif %}

    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit" value="logout" name="logout">Logout</button>
</form>


<h1>Users</h1>
<ul>
    {% for user in users %}
        <a href="{% url 'user:profile' user.get_short_name %}"><li>{{ user.get_full_name }}&nbsp;({{ user.get_short_name }})</li></a>
    {% endfor %}
</ul>
</body>
</html>

User/templates/User/profile_new.html
{% extends 'User/base.html' %}
{% load staticfiles %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'User/css/post_box.css' %}">

{% endblock %}
{% block nav %}
    <nav class="mdl-navigation mdl-layout--large-screen-only">
        <form action="" method="get">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                <label class="mdl-button mdl-js-button mdl-button--icon" for="sample6">
                    <i class="material-icons">search</i>
                </label>
                <div class="mdl-textfield__expandable-holder">
                    <input class="mdl-textfield__input" type="text" id="sample6" name="query">
                    <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
                </div>
            </div>
        </form>
        <a class="mdl-navigation__link" href="{% url 'user:create_article' %}">Create Post</a>
        <a class="mdl-navigation__link" href="{% url 'user:all_user' %}">Users</a>
        <a class="mdl-navigation__link" href="{% url 'user:profile' email %}">{{ username }}</a>
        <a class="mdl-navigation__link" href="{% url 'user:logout' %}">Logout</a>

    </nav>
{% endblock %}
{% block content %}
    {% if error_message %}
        <script>
            alert({{ error_message }});
        </script>
    {% endif %}
    {% if user_email %}
        <!--<h5 id="can_send_request">{{ is_friend }}</h5>-->
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored profile-button">{{ user_email }}</button>
    {% else %}
        <a href="{% url 'user:friends' %}"
           class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored profile-button">Friends</a>
        <div class="post-friends">
            <h5>Requests</h5>
            {% if friend_requests %}
                <form action="" method="post">
                    <ul>
                        {% for request in friend_requests %}
                            <li>
                                <span>{{ request.get_username }}</span>
                                <!-- Colored icon button -->

                                {% csrf_token %}
                                <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored"
                                        type="submit"
                                        name="accept_request" value="{{ request.requested_user_email }}">
                                    <i class="material-icons">done</i>
                                </button>

                            </li>
                        {% endfor %}
                    </ul>
                </form>
            {% else %}
                <ul>
                    <li>No Requests</li>
                </ul>
            {% endif %}
        </div>
    {% endif %}
    <div class="post-block">
        {% if posts %}
            {% for post in posts %}
                <div class="post-container">
                    <h2 class="post-title">{{ post.title }}</h2>
                    <hr>
                    <h3 class="post-body">{{ post.body }}</h3>
                    <div class="like-count">
                        <h5>{{ post.likes }}</h5>
                    </div>
                    {% if is_friend == "true" or create_post == "true" %}
                        <form action="" method="post">
                            {% csrf_token %}
                            <a class="mdl-button mdl-js-button mdl-button--icon edit btn-edit mdl-button--icon mdl-button--colored"
                               id="edit" href="{% url 'post:get_post' post.id %}">
                                <i class="material-icons ">forum</i>
                            </a>
                            <button class="mdl-button mdl-js-button mdl-button--icon edit btn-plus-one mdl-button--icon mdl-button--colored"
                                    id="description">
                                <i class="material-icons">description</i>
                            </button>
                            <button class="mdl-button mdl-js-button mdl-button--icon edit btn-plus-one mdl-button--icon mdl-button--colored"
                                    type="submit" id="plus-one" name="like_post" value="{{ post.id }}">
                                <i class="material-icons">thumb_up</i>
                            </button>
                            <div class="comment-count">
                                <h5>{{ post.comment_count }}</h5>
                            </div>
                            <h5></h5>
                        </form>
                    {% else %}
                        <a class="mdl-button mdl-js-button mdl-button--icon edit btn-edit"
                           id="edit">
                            <i class="material-icons ">forum</i>
                        </a>
                        <button class="mdl-button mdl-js-button mdl-button--icon edit btn-plus-one"
                                id="description">
                            <i class="material-icons">description</i>
                        </button>
                        <button class="mdl-button mdl-js-button mdl-button--icon edit btn-plus-one"
                                id="plus-one">
                            <i class="material-icons">thumb_up</i>
                        </button>
                        <div class="comment-count">
                            <h5>{{ post.comment_count }}</h5>
                        </div>
                        <h5></h5>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% if create_post == "false" and can_send_request == "true" %}
        <form action="" method="POST">
            {% csrf_token %}
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect"
                    type="submit" id="btn-add" name="add_friend" value="add_friend">Add Friend
            </button>
        </form>
    {% endif %}
    <script type="text/javascript">
        var is_friend = "{{ is_friend }}";
        //alert(is_friend);
    </script>
{% endblock %}

User/templates/User/profile_user.html
{% extends 'User/base.html' %}
{% block content %}
    <div class="post">

        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            Button
        </button>

    </div>
{% endblock %}

User/templates/User/register.html
{% extends 'User/base.html' %}
{% load staticfiles %}
{% block custom_style %}
    <link rel="stylesheet" href="{% static 'User/css/login_style.css' %}">
{% endblock %}

{% block nav %}
    <nav class="mdl-navigation mdl-layout--large-screen-only">

        <a class="mdl-navigation__link" href="{% url 'user:login' %}">Login</a>
        <a class="mdl-navigation__link" href="{% url 'user:register' %}">Register</a>


    </nav>
{% endblock %}
{% block content %}
    <div class="post">
        <div class="bar">
            <h3 class="login-title">Login User</h3>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <ul>
                {% for field in form %}
                    <li>
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            {{ field }}
                            <label class="mdl-textfield__label" for="{{ field.name }}">{{ field.label }}</label>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect"
                    type="submit" id="btn">{{ button_text }}</button>

        </form>
    </div>
{% endblock %}